name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        environment: [test310, test311, test312, test313]
    
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@19eac09b398e3d0c747adc7921926a6d802df4da  # v0.8.8
        with:
          cache: true

      - name: Tests
        run: >
          pixi run --environment ${{ matrix.environment }} test
        
      - name: Lint
        if: contains(${{ matrix.os }}, 'ubuntu')
        run: >
          pixi run --environment test310 lint



