name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        environment: [test310, test311, test312, test313]
    permissions:
      actions: none

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@97359467eae22a2d994114fe900db762fea86261  # v0.8.9
        with:
          cache: true

      - name: Tests
        run: >
          pixi run --environment ${{ matrix.environment }} test
