
name: test

on: [push, pull_request]

env:
  PIXI_VERSION: v0.47.0

# # Gave up -- could not figure out how to use environment variables :-(
# env:
#   # I got these from: https://github.com/prefix-dev/setup-pixi/blob/main/README.md
#   # they seem to keep it pretty up to date
#   SETUP_PIXI_VERSION: v0.8.1
#   PIXI_VERSION: v0.29.0

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        environment: [test310, test311, test312, test313]
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: latest
          cache: true
          # auth-host: prefix.dev
          # auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
      - run: pixi run --environment ${{ matrix.environment }} test
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: latest
          cache: true
          # auth-host: prefix.dev
          # auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
      - run: pixi run --environment test310 lint



